### ISSUE TITLE
Consider using react-testing-library for tests

### ISSUE THREAD

**Issue by viljark** [Iglu-OU/iglu-front#3]
https://kentcdodds.com/blog/testing-implementation-details
https://kentcdodds.com/blog/making-your-ui-tests-resilient-to-change
https://kentcdodds.com/blog/why-i-never-use-shallow-rendering
https://kentcdodds.com/blog/write-tests
https://medium.com/flatiron-labs/refactoring-an-enzyme-component-test-to-use-react-testing-library-f5c36da6716f
https://medium.com/@boyney123/my-experience-moving-from-enzyme-to-react-testing-library-5ac65d992ce
https://medium.com/@tang.apollo/tl-dr-why-recommending-react-testing-library-going-forwards-fc6cc3f05521

**Comment by antonaavik** [comment]
https://docs.google.com/document/d/19eIDuXVyphKbfh0SWvb_M4S8hUMYZ47auugoB9OrSRU/edit?usp=sharing Started to write short guidelines based on those articles

**Comment by kasparsuvi1** [comment]
Added React testing library based tests for components #14
